### ISSUE TITLE
Macport: do we need to specify "PortGroup cxx11 1.1"?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/packaging#12]
...in Portfile?

**Comment by galexv** [comment]
See 
<details><summary> <a href="https://github.com/macports/macports-ports/blob/b28195b5462e9e503794571e21fa68518553bfc5/_resources/port1.0/group/cxx11-1.1.tcl#L1,L11"> Macports cxx11 portgroup </a>
</summary>

```tcl
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
#
# This PortGroup introduces no new options. Simply including this
# PortGroup indicates that a port requires C++11
#
# Ideally the functionality of this PortGroup should be integrated into
# MacPorts base as a new option.

PortGroup compiler_blacklist_versions 1.0

# Compilers supporting C++11 are GCC >= 4.6 and clang >= 3.3.
```

</details>

This may address #9, #10, #11.

**Comment by egull** [comment]
I don't think we have a good way of testing this locally. I'd say just try,
and see if it sticks!

On Wed, Aug 22, 2018 at 11:02 AM, Alexander Gaenko <notifications@github.com

**Comment by galexv** [comment]
We did, it worked. Closing.
