### ISSUE TITLE
homebrew packages

### ISSUE THREAD

**Issue by egull** [ALPSCore/packaging#2]
Andrey, could you please update the homebrew release to 0.5.4?

**Comment by aeantipov** [comment]
Short update: a pull request is hanging at homebrew/science for 5 days:
https://github.com/Homebrew/homebrew-science/pull/3602
Waiting for them to merge it.

**Comment by egull** [comment]
mine has been hanging for 12 days at macports

**Comment by ryanlevy** [comment]
As a heads up, the `--with-check` option is depreciated, which could be a cause of the hold up. I get these warnings with `brew audit --strict --online alpscore` 

```
Use '--with-test' instead of '--with-check'. Migrate '--with-check' with `deprecated_option`.
C: 27: col 25: Don't use parentheses around a method call.
```

**Comment by aeantipov** [comment]
You get warnings for the old one, that is presently in homebrew. The one to be merged has "--with-test".
See https://github.com/Homebrew/homebrew-science/pull/3602/commits/1c3afe3b6e9a8fb0c3b39cf8f382bacd0af9a98e

**Comment by aeantipov** [comment]
Finished, alpscore 0.5.4 is in homebrew-science as of May 15
