### ISSUE TITLE
"Silent" dependency of ALPSCore port on MPI

### ISSUE THREAD

**Issue by galexv** [ALPSCore/packaging#5]
When ALPSCore port is built, it picks up OpenMPI if it is installed; however, there is no explicit dependency on MPI. My guess is that if the user uninstalls OpenMPI port, ALPSCore installation will become invalid.

We have a `+openmpi` variant of the `alpscore` port. I propose to detect whether the `+openmpi` variant is requested, and if not, disable the MPI build.

**Comment by egull** [comment]
don't think it's that easy: the mpi variants can also come from mpich or other mpi distributions.

**Comment by egull** [comment]
OK, I think I got it. Look at this:

 egull-mbp:~ egull$ port deps ALPSCore
 Full Name: ALPSCore @0.5.5_0
 Build Dependencies:   cmake
 Library Dependencies: boost, hdf5
 egull-mbp:~ egull$ port deps ALPSCore +openmpi
 Full Name: ALPSCore @0.5.5_0+openmpi
 Build Dependencies:   cmake
 Library Dependencies: boost, hdf5, openmpi-default

...so the mistake is that we try to compile with openmpi (or whatever mpi compiler is default) even when the mpi dependence is not specified.

That means that by default mpi should be switched off. And if someone specifies an mpi variant, it should be switched on with this:

compilers.choose    cc cxx
mpi.setup

if {[mpi_variant_isset]} {
  configure.args-replace --disable-mpi --enable-mpi
}

only that this is for configure.args. I wonder if something like this exists for cmake?

**Comment by galexv** [comment]
True, but according to [mpi portgroup](https://trac.macports.org/browser/trunk/dports/_resources/port1.0/group/mpi-1.0.tcl#L56) there are exactly 4 MPI variants: `mpich`, `mpich-devel`, `openmpi`, `openmpi-devel`. Moreover, [this line](https://trac.macports.org/browser/trunk/dports/_resources/port1.0/group/mpi-1.0.tcl#L47) suggests that it is possible to check "is an MPI variant requested?". 

And IMHO, if a user installs a version of MPI not from ports, she/he is qualified enough to install ALPSCore from sources too; better than `port install alpscore` magically picking up some MPI installation.

We may be able to go as far as installing an MPI variant by default, if there is an MPI port installed. Or maybe having an `+openmpi` variant installed by default.

**Comment by egull** [comment]
oh, by the way, this args-replace comes from this:
https://github.com/plumed/ports/blob/master/science/plumed/Portfile

**Comment by galexv** [comment]
I think 

```
configure.args-replace -DENABLE_MPI=OFF -DENABLE_MPI=ON
```

might just work.

**Comment by egull** [comment]
go for it!
